[project]
name = "dino-classifies-everything"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "torch",
    "torchvision",
    "transformers",
    "matplotlib",
    "tqdm",
    "poutyne",
    "pandas",
    "positional-encodings[pytorch]",
    "kagglehub>=1.0.0",
    "kaggle",
    "wandb>=0.25.1",
    "python-dotenv>=1.2.2",
]
